// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Slider2;
extern lv_obj_t *ui_BatteryPercentage;
extern lv_obj_t *ui_batteryint;
extern lv_obj_t *ui_Label2;
void ui_event_SpeedArc( lv_event_t * e);
extern lv_obj_t *ui_SpeedArc;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_TempSlider;
extern lv_obj_t *ui_TempLabel;
extern lv_obj_t *ui_SpeedLabel;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_background_png);   // assets/background.png
LV_IMG_DECLARE( ui_img_middle_circles_png);   // assets/middle_circles.png
LV_IMG_DECLARE( ui_img_right_empty_gauge_png);   // assets/right_empty_gauge.png
LV_IMG_DECLARE( ui_img_right_full_gauge_png);   // assets/right_full_gauge.png
LV_IMG_DECLARE( ui_img_speed_gauge_png);   // assets/speed_gauge.png
LV_IMG_DECLARE( ui_img_left_empty_gauge_png);   // assets/left_empty_gauge.png
LV_IMG_DECLARE( ui_img_left_full_gauge_png);   // assets/left_full_gauge.png
LV_IMG_DECLARE( ui_img_1926738670);   // assets/black-wifi-icon-32.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
